const SET_TIMER = "TIMER/SET";
const DECREASE_TIMER = "TIMER/DECREASE";
const RESET_TIMER = "TIMER/RESET";


const SET_TIMER_STYLE = "TIMER/STYLE";

export { SET_TIMER, DECREASE_TIMER, RESET_TIMER, SET_TIMER_STYLE };